version: '2.1'

services:
  kibana:
    image: 'kibana'
    depends_on:
      - elasticsearch
    ports:
      - '${KIBANA_PORT}:5601'

  elasticsearch:
    image: 'elasticsearch'
    volumes:
      - './docker/elasticsearch/config:/usr/share/elasticsearch/config'
      - './docker/elasticsearch/data:/usr/share/elasticsearch/data'
    ports:
      - '${ELASTICSEARCH_PORT}:9200'

  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '${ZOOKEEPER_PORT}:2181'

  kafka:
    image: 'wurstmeister/kafka'
    depends_on:
      - 'zookeeper'
    ports:
      - '${KAFKA_PORT}:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: '${KAFKA_HOST_NAME}'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  postgres:
    image: 'postgres'
    volumes:
      - './docker/postgres/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    ports:
      - '${POSTGRE_PORT}:5432'

  mysql:
    image: 'mysql/mysql-server'
    environment:
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
    ports:
      - '${MYSQL_PORT}:3306'

  php-fpm:
    image: php:fpm
    expose:
      - '9000'
    volumes:
      - './project:/var/www/html'

  nginx:
    image: 'nginx'
    depends_on:
      - php-fpm
    networks:
      default:
        ipv4_address: '${NGINX_IP}'
    volumes:
      - './docker/nginx/config:/etc/nginx/conf.d'
    volumes_from:
      - php-fpm
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: '${SUBNET_MASK}'
        gateway: '${GATEWAY}'
