<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends AbstractRepository
{
    public function filterByUserId($userId)
    {
        $postAlias = $this->getEntityAlias();
        $this->getQueryBuilder()
            ->where("{$postAlias}.author = :userId")
            ->setParameter('userId', $userId);

        return $this;
    }
}
