<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractRepository implements UserLoaderInterface
{
    /**
     * {@inheritDoc}
     */
    public function loadUserByUsername($username)
    {
        $userAlias = $this->getEntityAlias();
        return $this->newQueryBuilder()
            ->where("{$userAlias}.username = :username OR {$userAlias}.email = :username")
            ->setParameter('username', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
